var searchData=
[
  ['qpsk_0',['gdje jedna kasni za 214 simbola u odnosu na drugu, kako bi se generisao 28 GBaud QPSK',['../md__8aider_8chat_8history.html#autotoc_md76',1,'']]],
  ['qpsk_20eksperimentalni_20sistem_20sa_20nekoliko_20vlakana_2019_1',['Slika 5: 3 × 112Gbit/s DP-QPSK eksperimentalni sistem sa nekoliko vlakana. [19]',['../md__8aider_8chat_8history.html#autotoc_md67',1,'']]],
  ['qpsk_20mimo_20koncepta_20u_20višemodnom_20vlaknu_20dostupno_20je_20klikom_20na_20dugme_20objasni_20koncept_2',['Za pokretanje simulacije, potrebno je pokrenuti skriptu &lt;tt&gt;QPSK_MIMO.py&lt;/tt&gt;. Nakon pokretanja, korisnik može unijeti željene parametre simulacije u grafičkom sučelju (GUI). Simulacija se pokreće klikom na dugme &quot;Simuliraj&quot;. Rezultati simulacije i grafovi se prikazuju u odgovarajućim tabovima. Za brisanje svih grafova i rezultata, koristi se dugme &quot;Resetuj&quot;. Dodatne upute o korištenju simulacije mogu se pronaći klikom na dugme &quot;Pomoć&quot;, a detaljnije objašnjenje QPSK MIMO koncepta u višemodnom vlaknu dostupno je klikom na dugme &quot;Objasni koncept&quot;.',['../md__8aider_8chat_8history.html#autotoc_md201',1,'']]],
  ['qpsk_20mimo_20sistema_3',['QPSK MIMO sistema',['../md__8aider_8chat_8history.html#autotoc_md183',1,'Simulacija QPSK MIMO sistema'],['../md__8aider_8chat_8history.html#autotoc_md197',1,'Simulacija QPSK MIMO sistema'],['../md__8aider_8chat_8history.html#autotoc_md207',1,'Simulacija QPSK MIMO sistema'],['../md__r_e_a_d_m_e.html#autotoc_md224',1,'Simulacija QPSK MIMO sistema']]],
  ['qpsk_5fmimo_20py_4',['/add Kodovi\QPSK_MIMO.py',['../md__8aider_8chat_8history.html#autotoc_md180',1,'']]],
  ['qpsk_5fmimo_20py_20tt_20nakon_20pokretanja_20korisnik_20može_20unijeti_20željene_20parametre_20simulacije_20u_20grafičkom_20sučelju_20gui_20simulacija_20se_20pokreće_20klikom_20na_20dugme_20simuliraj_20rezultati_20simulacije_20i_20grafovi_20se_20prikazuju_20u_20odgovarajućim_20tabovima_20za_20brisanje_20svih_20grafova_20i_20rezultata_20koristi_20se_20dugme_20resetuj_20dodatne_20upute_20o_20korištenju_20simulacije_20mogu_20se_20pronaći_20klikom_20na_20dugme_20pomoć_20a_20detaljnije_20objašnjenje_20qpsk_20mimo_20koncepta_20u_20višemodnom_20vlaknu_20dostupno_20je_20klikom_20na_20dugme_20objasni_20koncept_5',['Za pokretanje simulacije, potrebno je pokrenuti skriptu &lt;tt&gt;QPSK_MIMO.py&lt;/tt&gt;. Nakon pokretanja, korisnik može unijeti željene parametre simulacije u grafičkom sučelju (GUI). Simulacija se pokreće klikom na dugme &quot;Simuliraj&quot;. Rezultati simulacije i grafovi se prikazuju u odgovarajućim tabovima. Za brisanje svih grafova i rezultata, koristi se dugme &quot;Resetuj&quot;. Dodatne upute o korištenju simulacije mogu se pronaći klikom na dugme &quot;Pomoć&quot;, a detaljnije objašnjenje QPSK MIMO koncepta u višemodnom vlaknu dostupno je klikom na dugme &quot;Objasni koncept&quot;.',['../md__8aider_8chat_8history.html#autotoc_md201',1,'']]],
  ['qpsk_5fmimo_5fgui_6',['QPSK_MIMO_GUI',['../class_q_p_s_k___m_i_m_o_1_1_q_p_s_k___m_i_m_o___g_u_i.html',1,'QPSK_MIMO']]]
];
