var searchData=
[
  ['ˇcak_20i_20na_20relativno_20srednjoj_20optiˇckoj_20snazi_20nelinearni_20efekti_20ovise_0',['efekti mogu postati bitni ˇcak i na relativno srednjoj optiˇckoj snazi. Nelinearni efekti ovise',['../md__8aider_8chat_8history.html#autotoc_md33',1,'']]],
  ['ˇcemu_20svaki_20kanal_20radi_20na_20jedinstvenoj_20valnoj_20duˇzini_20ovo_1',['izlazne optiˇcke kanale, pri ˇcemu svaki kanal radi na jedinstvenoj valnoj duˇzini. Ovo',['../md__8aider_8chat_8history.html#autotoc_md94',1,'']]],
  ['ˇcesta_20situacija_20u_20optiˇckim_20komunikacijama_2',['stima kada je dinamiˇcki opseg vrlo ˇsirok, ˇsto je ˇcesta situacija u optiˇckim komunikacijama.',['../md__8aider_8chat_8history.html#autotoc_md115',1,'']]],
  ['ˇcime_20se_3',['omogu´cava simultani prijenos viˇse podataka putem jednog optiˇckog vlakna, ˇcime se',['../md__8aider_8chat_8history.html#autotoc_md95',1,'']]],
  ['ˇcinjenice_20da_20u_20okruˇzenju_20visokog_20nivoa_20rasprˇsivanja_4',['storno multipleksiranje proizilazi iz ˇcinjenice da u okruˇzenju visokog nivoa rasprˇsivanja',['../md__8aider_8chat_8history.html#autotoc_md56',1,'']]],
  ['ˇcvorova_20mux_20u_20dva_20mux_20ulaza_5',['zasebno pojaˇcava prije nego ˇsto zavrˇsi u multiplekseru ˇcvorova (MUX-u).Dva MUX ulaza',['../md__8aider_8chat_8history.html#autotoc_md81',1,'']]],
  ['ˇsemama_20koje_20se_20oslanjaju_20na_20volumensku_20optiku_2012_6',['skupim MIMO procesorskim ˇsemama, koje se oslanjaju na volumensku optiku. [12]',['../md__8aider_8chat_8history.html#autotoc_md139',1,'']]],
  ['ˇsirenjem_20pulsa_20nelinearni_20efekti_20´ce_20izobliˇciti_20signal_20i_20ograniˇciti_20performanse_20sistema_2015_7',['ˇsirenjem pulsa. Nelinearni efekti ´ce izobliˇciti signal i ograniˇciti performanse sistema. [15]',['../md__8aider_8chat_8history.html#autotoc_md43',1,'']]],
  ['ˇsirinom_8',['na 80 kilometara su istraˇzena. ECL laser na talasnoj duˇzini od 1550,112 nm sa ˇsirinom',['../md__8aider_8chat_8history.html#autotoc_md70',1,'']]],
  ['ˇsirok_20ˇsto_20je_20ˇcesta_20situacija_20u_20optiˇckim_20komunikacijama_9',['stima kada je dinamiˇcki opseg vrlo ˇsirok, ˇsto je ˇcesta situacija u optiˇckim komunikacijama.',['../md__8aider_8chat_8history.html#autotoc_md115',1,'']]],
  ['ˇsirokopojasnog_10',['• Poˇsto je Massive MIMO (visoki redovi MIMO struja) kljuˇcan za budu´cnost ˇsirokopojasnog',['../md__8aider_8chat_8history.html#autotoc_md163',1,'']]],
  ['ˇsto_20je_20ˇcesta_20situacija_20u_20optiˇckim_20komunikacijama_11',['stima kada je dinamiˇcki opseg vrlo ˇsirok, ˇsto je ˇcesta situacija u optiˇckim komunikacijama.',['../md__8aider_8chat_8history.html#autotoc_md115',1,'']]],
  ['ˇsto_20je_20kljuˇcno_20za_12',['kapacitet prijenosa podataka, efikasnost spektra i otpornost na ˇsum, ˇsto je kljuˇcno za',['../md__8aider_8chat_8history.html#autotoc_md90',1,'']]],
  ['ˇsto_20minimizira_13',['koji koriste razliˇcite valne duˇzine su fiziˇcki i spektralno razdvojeni, ˇsto minimizira',['../md__8aider_8chat_8history.html#autotoc_md102',1,'']]],
  ['ˇsto_20omogu´cava_20slanje_20paralelnih_20tokova_20podataka_20i_20postizanje_20sposobnosti_14',['viˇse antena, ˇsto omogu´cava slanje paralelnih tokova podataka i postizanje sposobnosti',['../md__8aider_8chat_8history.html#autotoc_md58',1,'']]],
  ['ˇsto_20se_20koristi_20viˇse_20puteva_20izmedu_20predajnih_20i_20prijemnih_20antena_20pro_15',['gledu BER-a tako ˇsto se koristi viˇse puteva izmedu predajnih i prijemnih antena. Pro-',['../md__8aider_8chat_8history.html#autotoc_md55',1,'']]],
  ['ˇsto_20se_20preklapaju_20u_20frekvencijskom_20domenu_16',['ˇsto se preklapaju u frekvencijskom domenu.',['../md__8aider_8chat_8history.html#autotoc_md171',1,'']]],
  ['ˇsto_20su_20multiband_20ofdm_20uwb_20i_20wifi_20ieee_20802_2011ax_20kljuˇcna_20su_20za_17',['logija, kao ˇsto su multiband OFDM-UWB i WiFi IEEE 802.11ax, kljuˇcna su za',['../md__8aider_8chat_8history.html#autotoc_md175',1,'']]],
  ['ˇsto_20sve_20doprinosi_20gubitku_20odredenog_20vodenog_20moda_20na_18',['dova ili pomjeranje frekvencije, ˇsto sve doprinosi gubitku odredenog vodenog moda na',['../md__8aider_8chat_8history.html#autotoc_md37',1,'']]],
  ['ˇsto_20zavrˇsi_20u_20multiplekseru_20ˇcvorova_20mux_20u_20dva_20mux_20ulaza_19',['zasebno pojaˇcava prije nego ˇsto zavrˇsi u multiplekseru ˇcvorova (MUX-u).Dva MUX ulaza',['../md__8aider_8chat_8history.html#autotoc_md81',1,'']]],
  ['ˇsum_20ˇsto_20je_20kljuˇcno_20za_20',['kapacitet prijenosa podataka, efikasnost spektra i otpornost na ˇsum, ˇsto je kljuˇcno za',['../md__8aider_8chat_8history.html#autotoc_md90',1,'']]],
  ['ˇsuma_20kao_20i_20prilagodbu_20arhitekture_20prijemnika_20kako_21',['taciju naprednih metoda za smanjenje ˇsuma, kao i prilagodbu arhitekture prijemnika kako',['../md__8aider_8chat_8history.html#autotoc_md125',1,'']]],
  ['ˇsuma_20koji_20omogu´cavaju_20odrˇzavanje_20stabilnog_20i_22',['algoritme za predikciju i prilagodavanje ˇsuma, koji omogu´cavaju odrˇzavanje stabilnog i',['../md__8aider_8chat_8history.html#autotoc_md121',1,'']]],
  ['ˇsumove_20signali_23',['ljˇsana otpornost na medusobne smetnje signala (crosstalk) i vanjske ˇsumove. Signali',['../md__8aider_8chat_8history.html#autotoc_md101',1,'']]],
  ['ˇsumovi_20mogu_20dovesti_20to_20promjene_20svojstava_20signala_20performanse_20se_20mjere_20kroz_20stopu_24',['tiˇcki ˇsumovi mogu dovesti to promjene svojstava signala, performanse se mjere kroz stopu',['../md__8aider_8chat_8history.html#autotoc_md143',1,'']]],
  ['ˇzeljena_20stopa_20greˇsaka_20u_20bitovima_201_25',['da bi se realizovala ˇzeljena stopa greˇsaka u bitovima. [1]',['../md__8aider_8chat_8history.html#autotoc_md146',1,'']]],
  ['ˇzice_20gubici_20vlakna_20ograniˇcavaju_20udaljenost_20transmisije_20minilani_26',['(karakteristike optiˇcke ˇzice). Gubici vlakna ograniˇcavaju udaljenost transmisije (minilani',['../md__8aider_8chat_8history.html#autotoc_md41',1,'']]]
];
